name: testproj

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^3.0.0

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  cloud_firestore: ^0.11.0+2
  firebase_storage: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-icon.png
    - assets/background.jpg
    - assets/examples_photos/example_1.jpg
    - assets/examples_photos/example_2.jpg
    - assets/examples_photos/example_3.jpg
    - assets/examples_photos/example_4.jpg
    - assets/examples_photos/example_5.jpg
    - assets/people_photo.jpg